src/headpage/urls.py
from django.contrib import admin
from django.urls import include ,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social/', include('social.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/social/urls.py
from django.urls import path

from . import views
app_name = 'social'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # path('profile/<str:username>/', views.user_profile, name='profile'), #HOW IT SHOULD BE
    path('profile/', views.user_profile, name='profile'), #Old School, using GET Parameters to select the user
    path('upload_file/', views.upload_file, name='upload_file'), 
    path('edit_file/', views.edit_file, name='edit_file'), 
    path('delete_file/', views.delete_file, name='delete_file'), 
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('static/', views.static, name='static_files'),
]

src/social/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=16, unique=True)
    password = models.CharField(max_length=16)
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    about = models.TextField(default="",null=True)
    
    def __str__(self):
        return str(self.username)
        
class File(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=300, default="")
    path = models.CharField(max_length=3000, default="")
    is_public = models.BooleanField(default=True)
    
    def __str__(self):
        return "{} Owned by: {}".format(self.name,self.owner)

src/social/forms.py
from django import forms
from .models import File

class RegisterForm(forms.Form):
    username = forms.CharField(label='Username', max_length=16, required=True)
    password = forms.CharField(label='Password', max_length=16, required=True, widget=forms.PasswordInput)
    first_name = forms.CharField(label='First Name', max_length=64, required=True)
    last_name = forms.CharField(label='Last Name', max_length=64, required=True)

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=16, required=True)
    password = forms.CharField(label='Password', max_length=16, required=True, widget=forms.PasswordInput)

class EditProfileForm(forms.Form):
    password = forms.CharField(label='Password', max_length=16, widget=forms.PasswordInput, required=False, empty_value="")
    first_name = forms.CharField(label='First Name', max_length=64, required=False, empty_value="")
    last_name = forms.CharField(label='Last Name', max_length=64, required=False, empty_value="")
    about = forms.CharField(label="About", required=False , widget=forms.Textarea)
    profile_picture_from_file = forms.ImageField(label="Upload a Picture", required=False)
    profile_picture_from_url = forms.CharField(label='Or choose a Picture from an URL', required=False, empty_value="")

class FileUploadForm(forms.Form):
    file_upload = forms.FileField(label="Upload a new File", required=False)
    file_upload_name = forms.CharField(label='Rename File', max_length=300, required=False)
    file_upload_is_public = forms.BooleanField(label="Make Public?", required=False)
    #TODO List of user uploaded files with a booleanField to make public

class FileManagementForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['name', 'is_public','owner','path']
        widgets = {
            "owner": forms.HiddenInput(),
            "path": forms.HiddenInput(),
        }

src/social/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
#from django.template import loader
from django.conf import settings
from django.views import generic
from .models import User, File
from .forms import RegisterForm, LoginForm, EditProfileForm, FileUploadForm, FileManagementForm
import subprocess
import os
from django.db import connection
from .auth import authenticate_user, get_user, get_password_hash
from . import storage
import mimetypes

class IndexView(generic.ListView):
    template_name = 'social/index.html'
    context_object_name = 'users_alphabetical_list'

    def get_queryset(self):
        """Return the last five published questions."""
        try:
            return User.objects.order_by('username')
        except django.db.utils.OperationalError:
            return None

#God, just LOOK at this mess
def user_profile(request):
    logged_user = get_user(request.session.get('user_id'))

    if request.POST and logged_user != None:
        profile_form = EditProfileForm(request.POST,request.FILES)

        if profile_form.is_valid():
            # There are better ways to check for differences and update a model using a form
            # Check out the ModelForm() in the docs.
            pic_url = profile_form.cleaned_data["profile_picture_from_url"]
            new_password = profile_form.cleaned_data["password"]
            if len(pic_url)>0:
                # +++ VULNERABLE TO RCE (REMOTE CODE EXECUTION) +++
                subprocess.run( "wget {} -O {}{}{}.jpg".format(pic_url, settings.MEDIA_ROOT,"/avatars/",str(logged_user.id)), shell=True)
            #File uploaded in the field
            elif request.FILES.get("profile_picture_from_file",None) != None:
                # +++ VULNERABLE TO Unrestricted Upload of File with Dangerous Type +++
                storage.write_file(request.FILES["profile_picture_from_file"],"{}{}.jpg".format("/avatars/",str(logged_user.id)))
            if len(new_password) > 0:
                logged_user.password = get_password_hash(new_password)
            logged_user.first_name = profile_form.cleaned_data["first_name"]
            logged_user.last_name = profile_form.cleaned_data["last_name"]
            logged_user.about = profile_form.cleaned_data["about"]
            logged_user.save()
            
        return redirect(reverse("social:profile")+"?userid={}".format(logged_user.id))

    elif request.GET:
        try:
            #Check GET params 
            userid=request.GET.get('userid')
            #+++ VULNERABLE TO SQL INJECTION+++
            profile_user = list(User.objects.raw("SELECT  * FROM social_user WHERE id='{}'".format(userid)))[0]
            user_public_files = list(File.objects.filter(owner=userid, is_public=True))
        except:
            raise Http404("Profile does not exist")

        profile_form = None
        file_upload_form = None
        user_file_forms = []
        if logged_user == profile_user:
            profile_form = EditProfileForm(initial= {
                    "first_name":logged_user.first_name,
                    "last_name":logged_user.last_name,
                    "about":logged_user.about,})
            file_upload_form = FileUploadForm()
            user_files = list(File.objects.filter(owner=logged_user.id))

            for f in user_files:
                user_file_forms.append(FileManagementForm(instance=f))

        return render(request, 'social/profile.html', 
            {'user': profile_user,'edit_profile_form':profile_form,"file_upload_form":file_upload_form ,'user_public_files':user_public_files,'user_file_forms':user_file_forms})

def upload_file(request):
    logged_user = get_user(request.session.get('user_id'))
    if request.POST and logged_user != None:
        file_upload_form = FileUploadForm(request.POST,request.FILES)
        if file_upload_form.is_valid():
            if request.FILES.get("file_upload",None) != None:
                file_upload_name = file_upload_form.cleaned_data["file_upload_name"] or request.FILES["file_upload"].name
                file_upload_is_public = file_upload_form.cleaned_data["file_upload_is_public"]
                file_upload_path = "{}/{}/{}".format("files",logged_user.id,file_upload_name)
                # +++ VULNERABLE TO Unrestricted Upload of File with Dangerous Type +++
                storage.write_file(request.FILES["file_upload"],file_upload_path)
                f = File(name=file_upload_name,owner=logged_user,is_public=file_upload_is_public,path=file_upload_path)
                f.save()
        return redirect(reverse("social:profile")+"?userid={}".format(logged_user.id))

def edit_file(request):
    #TODO check for user login(?) , rename the file
    logged_user = get_user(request.session.get('user_id'))
    if request.POST and logged_user != None:
        file = File.objects.get(id=request.GET.get("id"))
        old_name = file.name
        old_path = file.path

        edit_form = FileManagementForm(request.POST,instance = file)
        edit_form.save()
        
        if old_name != file.name:
            file.path=file.path.replace(old_name,file.name)
            storage.move_file(old_path,file.path)

        file.save()
        return redirect(reverse("social:profile")+"?userid={}".format(logged_user.id))

def delete_file(request):
    logged_user = get_user(request.session.get('user_id'))
    if request.POST and logged_user != None:
        try:
            original_file = File.objects.get(id=request.GET.get("id"),owner=logged_user)
        except:
            #TODO don't return a 404, but a decent error message
            raise Http404("File does not exist")
        finally:
            storage.delete_file(original_file.path)
            original_file.delete()
            return redirect(reverse("social:profile")+"?userid={}".format(logged_user.id))

def static(request):
    if request.GET:
        #+++VULNERABLE TO PATH TRANSVERSAL+++
        # This is a pretty forced example, but it does demonstrate the vulnerability in itself
        path = os.path.join(settings.BASE_DIR,"social/static/social/",request.GET.get("file"))
        file = open(path,"rb")
        response = HttpResponse(file, content_type=mimetypes.guess_type(path)[0])
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(request.GET.get("file"))
        return response

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        error_message = ""
        #+++ VULNERABLE TO UNVALIDATED REDIRECTS +++
        url_to_redirect = request.session.pop("login_redirect",reverse('social:index'))
        if form.is_valid():
            curs = connection.cursor()

            username=request.POST.get('username')
            first_name=request.POST.get('first_name')
            last_name=request.POST.get('last_name')

            #+++ PASSWORD HASHED ON THE SERVERSIDE +++
            password=get_password_hash(request.POST.get('password'))
            try:
                # +++ VULNERABLE TO SQL INJECTION +++
                curs.executescript(
                    "INSERT INTO social_user ('username','password','first_name','last_name') VALUES ('{}','{}','{}','{}')".format(
                        username,password,first_name,last_name)
                )
                #+++ VULNERABLE TO UNVALIDATED REDIRECTS +++
                return redirect(url_to_redirect)
            #--- Generic exception = bad practice! ---
            except Exception as e:
                form = RegisterForm()
                error_message="ERROR! Username already taken!\n{}".format(e)
    else:
        if(request.GET.get("redirect")):
            request.session["login_redirect"] = request.GET.get("redirect")
        form = RegisterForm()
        error_message=""
    return render(request,'social/register.html',{'form': form,"error_message":error_message})

def login(request):
    if request.method=='POST':
        #+++ VULNERABLE TO UNVALIDATED REDIRECTS +++
        url_to_redirect = request.session.pop("login_redirect",reverse('social:index'))
        form = LoginForm(request.POST)
        error_message = ""
        if form.is_valid():
            user = authenticate_user(form.cleaned_data["username"],form.cleaned_data["password"])
            if user != None:
                request.session['user_id'] = user.id
                return redirect(url_to_redirect)
            form = LoginForm()
            error_message="Failure logging In!(Worng username/password?)\n"
    else:
        if(request.GET.get("redirect")):
            request.session["login_redirect"] = request.GET.get("redirect")
        form = LoginForm()
        error_message=""
    return render(request,'social/login.html',{'form': form,"error_message":error_message})

def logout(request):
    request.session.pop('user_id')
    #+++ VULNERABLE TO UNVALIDATED REDIRECTS +++
    url_to_redirect = request.GET.get("redirect",reverse('social:index'))
    return redirect(url_to_redirect)

src/social/templates/social/base.html
{% autoescape off %} <!-- +++ THIS WILL MAKE THE SITE VULNERABLE TO XSS +++ -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css"  href="{% static "social/style.css" %}">
    <title>{% block title %}HeadPage{% endblock %}</title>

</head>

<body>
    <div class="nav">
        {% block sidebar %}
        <ul class="nav">
            <l1><a class="nav" href="{% url 'social:index' %}">Home</a></l1>
            <l1>{% if request.session.user_id == None %}</l1>
            <l1><a class="nav" href="{% url 'social:login' %}?redirect={{request.get_full_path}}">Log-in</a></l1>
            <l1><a class="nav" href="{% url 'social:register' %}?redirect={{request.get_full_path}}">Sign-up</a></l1>
            <l1>{% else %}</l1>
            <l1><a class="nav" href="{% url 'social:profile'%}?userid={{request.session.user_id}}">Profile</a></l1>
            <l1><a class="nav" href="{% url 'social:logout'%}?redirect={{request.get_full_path}}">Log-out</a></l1>
            <l1>{% endif %}</l1>
        </ul>
        {% endblock %}
    </div>

    <div id="content" class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

<div class="footer">
    <p>Copyleft© 2020 DudeTrustUs Inc. No Rights Reserved</p>
    <a href="{% url 'social:static_files'%}?file=privacy.txt">Privacy Policy</a>
  </div>
{% endautoescape %} 

src/social/templates/social/index.html
{% extends 'social/base.html' %}
<!-- {% load static %} -->
<!-- <link rel="stylesheet" type="text/css" href="{% static 'poll/style.css' %}"> -->
{% block title %} Welcome to Headpage {% endblock %}

{% block content %}
    {% if users_alphabetical_list %}
        <ul class="center">
        {% for user in users_alphabetical_list %}
            <!-- Search for a URLConf path with the name 'profile', pass the function/method it calls the argument user.username -->
            <!-- <li> <a href="{#% url 'social:profile' user.username %#}"> -->
            <li style="list-style-type: none"> 
                <a class="user_list_item" href="profile/?userid={{user.id}}"> 
                    <img src="{{MEDIA_URL}}avatars/{{user.id}}.jpg" height="5%" width="5%" alt="Profile picture">
                    {{user.username}} ({{user.last_name}}, {{user.first_name}})
                </a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No users found!.</p>
    {% endif %}
{% endblock %}

src/social/templates/social/login.html
{% extends 'social/base.html' %}
{% block title %} Register {% endblock %}

{% block content %}
<form class="center" action="{% url 'social:login' %}" method="POST">
    <!-- TODO +++ VULNERABLE TO CSRF +++ -->
    {% csrf_token %}
    {{form}}
    {{error_message}}
    <input type="submit" value="Login!">
</form>
{% endblock %}

src/social/templates/social/profile.html
{% extends 'social/base.html' %}
{% block title %} {{user.username}}'s profile{% endblock %}
{% block content %}
{% load static %}

{% if edit_profile_form %}
<div class="horizontal_halves">
    <div class="left_half">
        <form class="center" action="{% url 'social:profile' %}?id={{user.id}}" enctype="multipart/form-data" method="POST">
            <h3>Edit File</h3>
            {% csrf_token %}
            {{edit_profile_form}}
            <input type="submit" value="Update Profile">
        </form>
    </div>

    <div class="right_half" >
        <h3>Upload File</h3>
        <form class="line_form" action="{% url 'social:upload_file' %}?id={{user.id}}" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{file_upload_form}}
            <input type="submit" value="Upload File">
        </form>

        <hr/>
        <h3>Current Files</h3>

        <!-- List all user saved Files -->
        {% for form in user_file_forms %}
            <div class="line_form">
                <a class="optional" href="{{MEDIA_URL}}{{form.instance.path}}">⤋</a> 
                <form class="line_form" action="{% url 'social:edit_file' %}?id={{form.instance.id}}" method="POST">
                    {% csrf_token %}
                    {{form}}
                    <input type="submit" value="Update File">
                    <!-- <a class="warning" href="{% url 'social:delete_file' %}?id={{form.instance.id}}">Delete File</a> -->
                </form>
                <form action="{% url 'social:delete_file' %}?id={{form.instance.id}}" method="POST">
                    {% csrf_token %}
                    <input class="warning" type="submit" value="Delete File">
                </form>
            </div>
        {% endfor %}
    </div>
</div>
<hr>
{% endif %}

<div class="center">
    <img src="{{MEDIA_URL}}avatars/{{user.id}}.jpg" height="200" width="200" alt="Profile picture">

    <h1>{{user.username}}</h1>
    <h2>{{user.first_name }} {{user.last_name}}</h2>
    <h3>About {{user.first_name}}</h3>
    <p>{{user.about}}</p>

    <!-- List all PUBLIC Files -->
    <h3>Public Files</h3>
    <ul>
        {% for file in user_public_files %}
        <li> <a href="{{MEDIA_URL}}{{file.path}}" download> {{file.name}} </a> </li>
        {% endfor %}
    </ul>

    {% endblock %}
</div>

src/social/templates/social/register.html
{% extends 'social/base.html' %}
{% block title %} Register {% endblock %}

{% block content %}
<form class="center" action="{% url 'social:register' %}" method="POST">
    <!-- TODO +++ VULNERABLE TO CSRF +++ -->
    {% csrf_token %}
    {{form}}
    {{error_message}}
    <input type="submit" value="Register !">
</form>
{% endblock %}